# https://github.com/nousresearch/hermes-agent
FROM nousresearch/hermes-agent:latest
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

ENV PATH="$PATH:/opt/hermes/.venv/bin"

RUN echo 'export PATH="$PATH:/opt/hermes/.venv/bin"' >> /etc/profile