# https://github.com/MariaDB/mariadb-docker
FROM mariadb:11.8
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN

# Using multiple databases with the offical docker image
COPY create-multiple-databases.sh /docker-entrypoint-initdb.d/