# https://github.com/docker-library/postgres.git
FROM docker.io/postgres:16-alpine
LABEL maintainer "https://github.com/yongxinL/docker-library"

# Add your setup here
# Example: RUN
COPY create-multiple-databases.sh /docker-entrypoint-initdb.d/