# https://github.com/docker-library/postgres.git
FROM docker.io/postgres:16-alpine
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN

# Using multiple databases with the offical docker image
COPY create-multiple-databases.sh /docker-entrypoint-initdb.d/