apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://secobvicmtrx:8428
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s

  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    access: proxy
    url: http://secobviclogs:9428
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s