# https://github.com/bulwarkmail/webmail
# Self-hosted JMAP webmail client for Stalwart Mail Server (Next.js)

ARG IMAGE_TAG=latest

FROM ghcr.io/bulwarkmail/webmail:${IMAGE_TAG}
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN
