# https://github.com/woodpecker-ci/woodpecker
ARG IMAGE_TAG=v3

FROM woodpeckerci/woodpecker-server:${IMAGE_TAG}
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN
