services:
    # Ollama - Running LLMs locally
    # https://github.com/ollama/ollama
    ollama:
        build:
            context: ../shared/ollama/
        environment:
            - TZ=${TIME_ZONE}
            - OLLAMA_HOST=0.0.0.0
            - OLLAMA_ORIGINS=*
            - OLLAMA_ORIGINS=app://obsidian.md*,moz-extension://*,chrome-extension://*,safari-web-extension://*
            - OLLAMA_CONTEXT_LENGTH=128000
        image: ollama
        networks:
            - subnet
        ports:
            - "11434:11434"
        volumes:
            - ${APPS_DATA}/webapps/ollama:/root/.ollama
        restart: unless-stopped