# https://github.com/goauthentik/authentik

ARG FORGE_TAG=16

FROM codeberg.org/forgejo/forgejo:${FORGE_TAG}
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN