# https://github.com/searxng/searxng.git
FROM searxng/searxng:latest
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN

# copy new default config
COPY settings.yml /etc/searxng/settings.yml 