# https://github.com/goauthentik/authentik

ARG AUTHK_TAG=2025.12

FROM ghcr.io/goauthentik/server:${AUTHK_TAG}
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN