# https://github.com/goauthentik/authentik

ARG IMAGE_TAG=2026.08

FROM ghcr.io/goauthentik/server:${IMAGE_TAG}
LABEL org.opencontainers.image.authors="yongxinL@outlook.com"

# Add your setup here
# Example: RUN